import json

import numpy as np
from sentence_transformers import SentenceTransformer
from tqdm import tqdm
import unicodedata

def normalize_text(text):
    result = unicodedata.normalize("NFKD", text)
    result = result.encode("ascii", "ignore").decode("ascii")
    return result

MODEL_NAME = "BAAI/bge-m3"

#MODEL_NAME = "intfloat/multilingual-e5-large-instruct"
#MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

PARTS = [
        "early",
        "later",
        "late",
        "march",
        "grand",
        "duchy",
        "republic",
        "kingdom",
        "federation",
        "federative",
        "state",
        "shogunate",
        "khanate",
        "caliphate",
        "triple",
        "alliance",
        "clan",
        "lordship",
        " the ",
        "grand",
        "duchy",
        "order",
        "margraviate",
        "electorate",
        "confederation",
        "league",
        "commonwealth",
        "government",
        " of ",
        "islamic",
        "federal",
        "tribes",
        "tsardom",
        "sultanate",
        "emirate",
        "empire",
        "crown",
        "duchy",
        "principality",
        "democratic",
        "people's",
        "ancient",
        "new ",
        "civilization",
        "imperial",
        "dynastic",
        "dynasty",
        "federal",
        "socialist",
        "peoples",
        "union",
        "republics",
        "united",
        "states",
        "oriental",
        "trust",
        "territory",
        "islamic",
        #"arab",
        "great",
        "democratic",
        "socialist",
        "peoples",
        "soviet",
        "north",
        "continental",
        "people",
        "petty",
        "northern",
        "late",
        "period",
        "southern",
        "indegenous",
        "northeastern",
        "northwestern",
        "southeastern",
        "southwestern",
        "culture",
        "city-state",
        "eastern",
        "western",
        "central",
        "east",
        "west"
]


class NamesSearch:
    def __init__(self, names_list):
        self.model = None
        self._embedding_cache = {}
        self.update_names(names_list)

    def update_names(self, names_list):
        normalized_names = [
            name.strip().replace("\n", " ").lower()
            for name in names_list
        ]
        self.names_list = normalized_names

        # Модель грузим с диска один раз и переиспользуем между вызовами
        if self.model is None:
            self.model = SentenceTransformer(MODEL_NAME)

        # Кодируем только те имена, эмбеддинги которых ещё не в кэше
        new_names = [name for name in set(normalized_names) if name not in self._embedding_cache]
        if new_names:
            new_embeddings = self.model.encode(
                new_names,
                batch_size=64,
                normalize_embeddings=True,
                show_progress_bar=True,
            )
            for name, embedding in zip(new_names, new_embeddings):
                self._embedding_cache[name] = embedding

        self.embeddings = np.array([self._embedding_cache[name] for name in normalized_names])

    def search_for_similar_names(self, name, 
                                 min_similarity=0.9, 
                                 min_similarity_second=0.9, verbose=False):
        
        """Ищет похожие имена государств для заданного имени и возвращает similar_names."""
        query = normalize_text(name)
        query_processed = query.lower()
        query_embedding = self.model.encode(
            query_processed,
            batch_size=64,
            normalize_embeddings=True,
            show_progress_bar=verbose,
        )

        scores = self.embeddings @ query_embedding
        # Сортируем от наиболее похожего к наименее похожему
        indices = np.argsort(scores)[::-1]

        list_of_similar = []
        for index in indices[:100]:
            candidate_name = self.names_list[index]
            score = scores[index]
            if score > min_similarity:
                if verbose:
                    print(f"{scores[index]:.4f} | {candidate_name}")
                list_of_similar.append(candidate_name)
                temp_query_embedding = self.model.encode(
                    candidate_name,
                    batch_size=64,
                    normalize_embeddings=True,
                    show_progress_bar=verbose,
                )
                scores_temp = self.embeddings @ temp_query_embedding
                # Сортируем от наиболее похожего к наименее похожему
                indices_temp = np.argsort(scores_temp)[::-1]
                for index_temp in indices_temp[:10]:
                    name_temp = self.names_list[index_temp]
                    if name_temp not in list_of_similar:
                        list_of_similar.append(name_temp)
                        score_temp = scores_temp[index_temp]
                        if verbose and score_temp > min_similarity and name_temp.lower() != candidate_name.lower():
                            print(f"    {scores_temp[index_temp]:.4f} | {name_temp}")

        cleared_list = []
        cleared_dict = {}
        for candidate_name in list_of_similar:
            cleared_query = candidate_name.lower()
            for part in PARTS:
                cleared_query = cleared_query.replace(part, "")
            cleared_query = cleared_query.strip()
            cleared_list.append(cleared_query)
            if cleared_query not in cleared_dict:
                cleared_dict[cleared_query] = []
            cleared_dict[cleared_query].append(candidate_name)

        main_processed_query = query.lower()
        for part in PARTS:
            main_processed_query = main_processed_query.replace(part, "")
        main_processed_query = main_processed_query.strip()

        similar_names = []
        if not cleared_list:
            return similar_names

        temporary_embeddings = self.model.encode(
            cleared_list,
            batch_size=64,
            normalize_embeddings=True,
            show_progress_bar=verbose,
        )

        main_query_embedding = self.model.encode(
            main_processed_query,
            normalize_embeddings=True,
        )

        scores = temporary_embeddings @ main_query_embedding
        top_indices = np.argsort(scores)[::-1][:10]

        for idx in top_indices:
            if verbose:
                print(scores[idx], cleared_list[idx])
            if scores[idx] > min_similarity_second:
                for candidate_name in cleared_dict[cleared_list[idx]]:
                    if candidate_name.title() not in similar_names:
                        similar_names.append(candidate_name.title())
        if normalize_text(name) in self.names_list:
            similar_names.append(normalize_text(name).title())
        return similar_names

if __name__ == "__main__":

    names = [
        "France",
        "Morocco",
        "Brazil",
        "Tokugawa Shogunate",
        "Japan",
        "Mataram Sultanate",
        "Mataram",
        "Dutch Empire",
        "Great Britain",
        "United Kingdom",
        "Indonesia",
        "Vietnam",
        "India",
        "Portugal",
        "South Africa",
        "Qing",
        "China",
        "Pakistan",
        "United States",
        "Ethiopia",
        "Italy",
        "Ottoman Empire",
        "Hejaz",
        "Nejd",
        "Saudi Arabia",
        "Cyprus",
        "Cameroon",
        "Russian Empire",
        "Russian Soviet Federative Socialist Republic",
        "Soviet Union",
        "Russia",
        "Oman",
        "Iran",
        "Granada",
        "Colombia",
        "Mughal Empire",
        "Maratha Empire",
        "Algeria",
        "Bangladesh",
        "Spain",
        "Philippines",
        "Belgium",
        "Belgian Congo And Ruanda-Urundi",
        "Burundi",
        "Somali",
        "Ukraine",
        "Bukhara",
        "Afghanistan",
        "Ilkhanate",
        "Chobanids",
        "Jalayirids",
        "Timurid Empire",
        "Kara Koyunlu",
        "Aq Qoyunlu",
        "Persia",
        "Yoruba",
        "Oyo",
        "Niger",
        "Nigeria",
        "Nepal",
        "Iberian Union",
        "Mexico",
        "Burma",
        "Greece",
        "Turkey",
        "North Korea",
        "Zimbabwe",
        "Canada",
        "Confederate States",
        "England",
        "Kenya",
        "Korea",
        "South Korea",
        "Vijayanagara Empire",
        "Mysore",
        "Nizam",
        "Cote Divoire",
        "Delhi Sultanate",
        "Company Raj",
        "Germany",
        "Togo",
        "Plymouth Colony",
        "Egypt",
        "Rohilla",
        "Argentina",
        "Chola",
        "Kakatiya",
        "Kakatiya Dynasty",
        "Reddi",
        "Golconda",
        "United States Of Indonesia",
        "Venezuela",
        "Rattanakosin",
        "Thailand",
        "Ming",
        "Shun",
        "Upper Volta",
        "Burkina Faso",
        "Kedah",
        "Malaya",
        "Malaysia",
        "United Arab Republic",
        "Trinh Lords",
        "Joseon",
        "Angola",
        "Madagascar",
        "Rwanda",
        "Texas",
        "Ashanti",
        "Ghana",
        "Rio De La Plata",
        "Hoysala",
        "Kolathunadu",
        "Kolathiri",
        "Syria",
        "Iraq",
        "Guatemala",
        "Uzbekistan",
        "Azerbaijan",
        "Kalmar Union",
        "Sweden",
        "Finland",
        "Peru",
        "Holy Roman Empire",
        "Habsburg Monarchy",
        "Netherlands",
        "Durrani Empire",
        "Uganda",
        "Australia",
        "Guinea",
        "Papua New Guinea",
        "Ecuador",
        "Ceylon",
        "Sri Lanka",
        "Tunisia",
        "Hyderabad State",
        "Hungary",
        "Moldavia",
        "United Principalities",
        "Romania",
        "Prussia",
        "Nations",
        "West Germany",
        "Dagbon",
        "Kalat",
        "Talpur",
        "Castile",
        "Sokoto Caliphate",
        "Bamum",
        "Poland-Lithuania",
        "Warsaw",
        "Poland",
        "Aztec Empire",
        "Independent Bhutan",
        "Bhutan",
        "Tibet",
        "Yuan",
        "Chile",
        "Sunda",
        "Cirebon Sultanate",
        "Cirebon",
        "Ashikaga Shogunate",
        "Oda Nobunaga",
        "Toyotomi",
        "United States Usamgik",
        "Benin",
        "Nupe",
        "Viet Minh",
        "Travancore",
        "Polonnaruwa",
        "Kalinga",
        "Dambadeniya",
        "Yapahuwa",
        "Kurunegala",
        "Gampola",
        "Kotte",
        "Sitawaka",
        "Kandy",
        "Sikh Misls",
        "Hawaii",
        "Sudan",
        "South Sudan",
        "Byzantine Empire",
        "Latin Empire",
        "Bulgaria",
        "Nicaea",
        "Serbia",
        "Venice",
        "Danes",
        "North Sea Empire",
        "Zambia",
        "Haiti",
        "Musunuri",
        "British East India Company",
        "Tungning",
        "Dimasa",
        "Kachari",
        "Ahom",
        "Aro",
        "Goryeo",
        "Yemen",
        "Cuba",
        "Denmark-Norway",
        "Denmark",
        "Allied Occupation Zone",
        "Bikaner",
        "Bikaner State",
        "Mossi",
        "Russian Republic",
        "Golden Horde",
        "Moldavian Democratic Republic",
        "Moldova",
        "Seljuk",
        "Khwarazm",
        "Aydinids",
        "Toungoo",
        "Sindh",
        "Dahomey",
        "Ayyubids",
        "Abbasids",
        "Rasulid Sultanate",
        "Mamluk",
        "Rasulid Dynasty",
        "Zaidi",
        "Zaydi Imamate",
        "Cambodia",
        "Khmer Republic",
        "Djibouti",
        "Moscow Rus",
        "Nkwerre Polity",
        "Oyo Empire",
        "Rashidun Caliphate",
        "Umayyad Caliphate",
        "Tanganyika",
        "Tanzania",
        "Merina",
        "Liberia",
        "Liao",
        "Jin",
        "Jin Dynasty",
        "Mongol Empire",
        "Honduras",
        "Shimosa Province",
        "Ghaznavids",
        "Ghurids",
        "Austria-Hungary",
        "Czechoslovakia",
        "Czechia",
        "Pagaruyung",
        "Minangkabau Sultanate",
        "Minangkabau",
        "Madurai",
        "Istanbul Allied Occupation",
        "Bima",
        "Dompu Sultanate",
        "Congo",
        "Western Han",
        "Eastern Han",
        "Changsha Commandery",
        "Eastern Wu",
        "Western Jin",
        "Eastern Jin",
        "Liu Song",
        "Southern Qi",
        "Liang",
        "Chen",
        "Sui",
        "Sui Dynasty",
        "Tang",
        "Zhou",
        "Tang Dynasty",
        "Chu",
        "Chu Ten",
        "Southern Tang",
        "Song",
        "New Zealand",
        "Cordoba",
        "Al-Andalus",
        "Maghrawa",
        "Almoravids",
        "Almohad",
        "Cyrene",
        "Macedonian Empire",
        "Cassander",
        "Ptolemaic Egypt",
        "Roman Republic",
        "Roman Empire",
        "Okinawa Chiefdoms",
        "Ryukyu",
        "Chuzan",
        "Ukrainian Peoples Republic",
        "Leon",
        "Antes",
        "Avar Khaganate",
        "Polianians",
        "Khazar Khaganate",
        "Kievan Rus",
        "Lithuania",
        "Cossack Hetmanate",
        "Dutch",
        "Formosa",
        "Yuan Dynasty",
        "Northern Yuan",
        "Dzungar Khanate",
        "KIche",
        "Kiche",
        "Maya",
        "Magyars",
        "Talpur Dynasty",
        "Mahan",
        "Baekje",
        "Silla",
        "Unified Silla",
        "Serbs, Croats And Slovenes",
        "Yugoslavia",
        "Serbia And Montenegro",
        "Macedonia",
        "Pandya",
        "Pandya Dynasty",
        "Madurai Sultanate",
        "Thanjavur",
        "Gabon",
        "Cao Wei",
        "Northern Sixteen",
        "Northern Wei",
        "Eastern Wei",
        "Northern Qi",
        "Northern Zhou",
        "Later Liang",
        "Later Tang",
        "Later Jin",
        "Later Han",
        "Buenos Aires State",
        "British Raj",
        "Riograndense Republic",
        "Bijapur",
        "Paraguay",
        "Jammu And Kashmir",
        "Dominica",
        "Dominican Republic",
        "Savoy",
        "Two Sicilies",
        "Piedmont",
        "Canik Beyliks",
        "Eretna",
        "Mali",
        "Senegal",
        "Westphalia",
        "Hanover",
        "Kenmu",
        "Saionji Clan",
        "Western Roman Empire",
        "Visigothic",
        "Cordoba Emirate",
        "Cordoba Caliphate",
        "Taifa Of Denia",
        "Denia",
        "Aragon",
        "United States Military Occupation",
        "Sine",
        "Luhansk Peoples Republic",
        "Khiva Khanate",
        "Later Zhou",
        "Gallic Empire",
        "Carolingian Empire",
        "West Francia",
        "Bahmani",
        "Ahmadnagar",
        "Gujarat",
        "Vaghela Dynasty",
        "Hueda",
        "Whydah",
        "Costa Rica",
        "Mozambique",
        "Venad",
        "Banjar",
        "Panduranga",
        "Bengal",
        "Nanhai Commandery",
        "Eastern Jin Dynasty",
        "Liang Dynasty",
        "Chen Dynasty",
        "Southern Han",
        "Nasrids",
        "Hoysala Empire",
        "Chad",
        "Kazakhstan",
        "Chupicuaro Culture",
        "Teotihuacan",
        "Libya",
        "Kazakh Khanate",
        "United Arab Emirates",
        "Satavahana Empire",
        "Post-Satavahana Deccan States",
        "Western Satraps",
        "Vakataka",
        "Gupta Empire",
        "Chalukyas Of Badami",
        "Chalukya",
        "Rashtrakuta Dynasty",
        "Yadava",
        "Deccan",
        "Khandesh",
        "Wu",
        "Wuyue",
        "Kyrgyzstan",
        "Cuanman",
        "Dali",
        "Marshalleses",
        "Marshall Islands",
        "Futa Jallon",
        "Wanga",
        "Rum",
        "Ayutthaya",
        "East Germany",
        "Chahamana",
        "Cayor",
        "Champa",
        "Tenochtitlan",
        "Mexica",
        "Azcapotzalco",
        "Tepanec",
        "Turkmenistan",
        "Serb-Croat-Slovene State",
        "Bosnia And Herzegovina",
        "Sicily",
        "Allied Military Government",
        "Chera",
        "Mushika",
        "Kottayam",
        "Chajoma",
        "Kaqchikel",
        "Tiwanaku",
        "Aymara",
        "Inca Empire",
        "Aymara Polities",
        "Bolivia",
        "Qin",
        "Taishan Commandery",
        "West Ukrainian Peoples Republic",
        "Yuzhang Commandery",
        "United States Army Military Government In Korea",
        "Betsimisaraka",
        "Boina",
        "Sub-Roman Britain",
        "Mercia",
        "Wessex",
        "Eastern Roman Empire",
        "Apulia",
        "Parthenopea",
        "Papal States",
        "Marwar",
        "Dyfed",
        "Wales",
        "Confederation Of Rhine",
        "Bavaria",
        "Banten",
        "Qutb Shahi",
        "Berar",
        "Wurttemberg",
        "German Confederation",
        "Zoque",
        "Saxons",
        "East Francia",
        "Chile Patria Vieja",
        "Pueblo Peoples",
        "Acoma Pueblo",
        "Hopi",
        "Ancestral Puebloans",
        "Pueblo",
        "Tlatelolco",
        "Canari",
        "Alto Peru",
        "Siberian Khanate",
        "Carnatic Sultanate",
        "Panama",
        "Don Republic",
        "Kuaiji Commandery",
        "Chaedini",
        "Hordar",
        "Vossingi",
        "Petty  Voss",
        "Norway",
        "Sweden-Norway",
        "Francia",
        "Viking Normandy",
        "Duchy Of Brittany",
        "Elisyces",
        "Massalia",
        "Ostrogoths",
        "Provence",
        "Buyids",
        "Muzaffarids",
        "Reddi Dynasty",
        "Georgia",
        "Abkhazia",
        "Ratanpur",
        "Keladi",
        "Shewa",
        "Nicaragua",
        "Gonja",
        "Majapahit",
        "Demak Sultanate",
        "Demak",
        "Yogyakarta Sultanate",
        "Benevento",
        "Salerno",
        "Batswana",
        "Botswana",
        "Teutonic Order",
        "Wadai Empire",
        "Wadai",
        "Funan",
        "Chenla",
        "Dvaravati",
        "Khmer",
        "Sukhothai",
        "Dumnonii",
        "Fante Confederacy",
        "Ahmadnagar Sultanate",
        "Hausa States",
        "Taiwan",
        "Ran Wei",
        "Volga Bulgaria",
        "Kazan Khanate",
        "Myinsaing",
        "Pinya",
        "Hanthawaddy",
        "Ava",
        "Mewar",
        "Vaghela",
        "Duchy Of Normandy",
        "Malacca",
        "Johor Sultanate",
        "Pahang",
        "Malacca Sultanate",
        "Johor",
        "Denkyira",
        "Aneho",
        "Austria",
        "Shimabara Rebels",
        "Gaza Empire",
        "Maitraka Dynasty",
        "Saindhava Dynasty",
        "Rashtrakuta Empire",
        "Chudasama Dynasty",
        "Junagadh",
        "Jeolla Province",
        "Medang",
        "Kahuripan",
        "Janggala",
        "Kediri",
        "Singhasari",
        "Lesotho",
        "Rebel Control",
        "Israel",
        "Antigonids",
        "Seleucid Empire",
        "Parthian Empire",
        "Sasanian Empire",
        "Injuids",
        "Fiji",
        "Fijian",
        "Slovakia",
        "Montenegro",
        "Kosovo",
        "Gowa-Tallo",
        "Yettishar",
        "Carthage",
        "Odoacer",
        "Duchy Of Benevento",
        "Aghlabids",
        "Bari Emirate",
        "Malawi",
        "Kabul",
        "East Timor",
        "United Nations",
        "El Salvador",
        "Khasa",
        "Khas",
        "Malla",
        "Jumla",
        "Kathmandu",
        "Baise Rajya",
        "Dailekh",
        "Baise",
        "Lombards",
        "Jinhan",
        "Negeri Sembilan",
        "Gwynedd",
        "Pomeranians",
        "Wolinianians",
        "Early Polish State",
        "Pomerania",
        "Carystus",
        "Achaemenid Empire",
        "Athens",
        "Sparta",
        "Lysimachus",
        "Pergamon",
        "Svear",
        "Suiones",
        "Magna Graecia",
        "Taormina",
        "Epirus",
        "Syracuse",
        "Vandals And Alans",
        "Fatimids",
        "Sicily Emirate",
        "Rip",
        "Jaunpur Sultanate",
        "Belarus",
        "Caucasian Imamate",
        "Zayyanids",
        "Hafsids",
        "Gujarat Sultanate",
        "Eastern Zhou",
        "Ba Commandery",
        "Shu Han",
        "Cheng-Han",
        "Western Shu",
        "Shu",
        "Manipur",
        "Jiangxia Commandery",
        "Gengshi Emperor",
        "Kalabhra",
        "Tamil/Andhra Dynasties",
        "Pallava Dynasty",
        "Western Wei",
        "Tangut",
        "Western Xia",
        "Ajuran Sultanate",
        "Malindi",
        "Pate",
        "Oromo",
        "Omani Empire",
        "Zanzibar",
        "Deira",
        "Northumbria",
        "Jorvik",
        "Angevin Empire",
        "Kushan Empire",
        "Kidarites",
        "Hephthalites",
        "Gokturks",
        "Turgesh Khaganate",
        "Turgesh",
        "Chagatai Khanate",
        "Shaybanids",
        "Sardinia",
        "Pisa",
        "Burhan Al-Din",
        "Suebi",
        "Taifa Of Jaen",
        "Indo-Scythians",
        "Alchon Huns",
        "Maukhari Dynasty",
        "Pushyabhuti Dynasty  Thanesar",
        "Harshavardhana",
        "Pushyabhuti",
        "Gurjara-Pratihara",
        "Pratihara Dynasty",
        "Bahmani Sultanate",
        "Kuwait",
        "Nabataean",
        "Ulaid",
        "Celtic La Tene Culture",
        "Ireland",
        "Lordship Of Ireland",
        "Tsang",
        "Ganden Phodrang",
        "Atropatene",
        "Rashidun",
        "United Provinces",
        "Minyue",
        "Anlo",
        "Berar Sultanate",
        "Mauritius",
        "Hamidids",
        "Leinster",
        "Catalonia",
        "Hamath City-State",
        "Amorites",
        "Yamhad",
        "Hittite Empire",
        "Mitanni",
        "Hamath",
        "Assyria",
        "Neo-Assyrian Empire",
        "Babylon",
        "Armenia",
        "Palmyrene Empire",
        "Tulunid Dynasty",
        "Hamdanids",
        "Paramara",
        "Malwa",
        "Restored Han Gengshi Emperor",
        "Bangangte",
        "Yucatan",
        "Gorkha",
        "Qi",
        "Xin Dynasty",
        "Thuringia",
        "Rhine",
        "North German Confederation",
        "Zhao",
        "Qin Dynasty",
        "Redones",
        "Hallstatt Culture",
        "Armorica",
        "Franks",
        "Wurzburg",
        "Savantvadi State",
        "Srivijaya",
        "Samudra Pasai",
        "Aceh",
        "Judah",
        "Ghassulian Culture",
        "Levantine Culture",
        "Canaanites",
        "Ancient Egypt",
        "Edom",
        "Nabataea",
        "Dadan",
        "Lihyan",
        "Mont Bego Bronze Age Culture",
        "Maritime Alps Bronze Age Culture",
        "Polada Culture",
        "Ligurian Bronze Age Culture",
        "Mont Bego Culture",
        "Ligures",
        "Urnfield Culture",
        "Ligurians",
        "Ecdini",
        "Acarnanians",
        "Acarnania",
        "Macedon",
        "Aetolia",
        "Gallaecians",
        "Grovii",
        "Sogdia",
        "Greco-Bactrian",
        "Yuezhi",
        "Samanid Empire",
        "Chagatai",
        "Mongolia",
        "Transcaucasian Democratic Federative Republic",
        "Tarascan",
        "Bavarii",
        "Duchy Of Bavaria",
        "Trebizond",
        "Kano",
        "Germiyanids",
        "Rugii",
        "Wielbark Culture",
        "Goths",
        "Lemovii",
        "Wolinians",
        "Veleti",
        "Wolinian Tribe",
        "Wolinian Polity",
        "Bryneich",
        "Bernicia",
        "Lindsey",
        "Danelaw",
        "Swedes Sviar",
        "Powys",
        "Chahamanas Of Shakambhari",
        "Suri Empire",
        "Brunei",
        "Milan",
        "Florence",
        "Tuscany",
        "Etruria",
        "Central Italy",
        "Welser",
        "Karamanids",
        "Lelang Commandery",
        "Goguryeo",
        "Protectorate General To Pacify East",
        "Balhae",
        "Taifa Of Seville",
        "Native Americans",
        "Tajikistan",
        "Middle Francia",
        "Latvia",
        "Menteshe",
        "Sierra Leone",
        "Jolof",
        "Jordan",
        "Eastern Ganga",
        "Eastern Ganga Dynasty",
        "Gajapati",
        "British Central Africa Protectorate",
        "Temne",
        "Loko",
        "Huaylas",
        "Asturias",
        "Galicia",
        "Kaarta",
        "Gajaaga",
        "Kabardia",
        "Don Cossacks",
        "Dai Viet",
        "Ho",
        "Later Le Dynasty",
        "Maori",
        "Leon And Castile",
        "Adamawa Emirate",
        "Colima",
        "Purepecha State",
        "Cocolan State",
        "Cape Verde",
        "Norse",
        "Sanwi",
        "Taifa Of Granada",
        "Verona",
        "Central Africa",
        "Central African Republic",
        "Gambia",
        "Royal Niger Company",
        "Scotland",
        "Karasi",
        "Hoysala Dynasty",
        "Querandi",
        "Orange Free State",
        "Toltec",
        "Samatata",
        "Pala",
        "Khilji",
        "Khurda",
        "Cochin",
        "Vadakkumkur",
        "Order Of Saint John",
        "Malta",
        "Qatna",
        "Emesene",
        "Salamis",
        "Kition",
        "Kourion",
        "Salamis Cyprus",
        "Alashiya",
        "Idalion",
        "Teuchitlan",
        "Bisanthe",
        "Thyni",
        "Odrysia",
        "Gauls",
        "Iberia",
        "Kartli",
        "Katyuri",
        "Kumaon",
        "ChengHan",
        "Ganjam",
        "Luang Prabang",
        "Akwamu",
        "Crimean Khanate",
        "Crimean Peoples Republic",
        "Uruguay",
        "Oda Clan",
        "Brigantes",
        "Orleans",
        "Pontus",
        "Vandals",
        "Rustamids",
        "Zirids",
        "Hammadid",
        "Hungarian State",
        "Bornu Empire",
        "Lan Na",
        "Jodhpur State",
        "Bonny",
        "Ahoada",
        "Sankaran",
        "Kutch",
        "Caxcan",
        "Nogai Horde",
        "Taifa Of Murcia",
        "Kalbids",
        "Nezak Huns",
        "Turk Shahi",
        "Hindu Shahi",
        "Sayyid Dynasty",
        "Manavadar",
        "Albania",
        "Guinea-Bissau",
        "Norse Settlements Faroe Islands",
        "Faroese Althing",
        "Faroese Commonwealth",
        "Faroese Norse",
        "Maurya",
        "Salankayana Dynasty",
        "Vishnukundina Dynasty",
        "Elam",
        "Sumer",
        "Akkadian Empire",
        "Larsa",
        "Cimmerians",
        "Lydia",
        "Galatia",
        "Bithynia",
        "Phoenicia",
        "Castellieri Culture",
        "Illyrians",
        "Histri",
        "Histrians",
        "Wessex Culture",
        "Deverel-Rimbury Culture",
        "Bronze Age Britons",
        "Canaan",
        "United Monarchy",
        "Messenia",
        "Messene",
        "Achaean League",
        "Burgundy",
        "Upper Burgundy",
        "Duchy Of Burgundy",
        "Croatia",
        "Iceland",
        "Saruhan",
        "Unclaimed",
        "Paramara Dynasty",
        "Alans",
        "Waliate Of Al-Andalus",
        "Taifa Of Toledo",
        "Saxony",
        "Arcadia",
        "Slavs",
        "Sclavenes",
        "Estonia",
        "Numidia",
        "Awraba",
        "Ibadi Imamate Of Ifriqiya",
        "Khorasan",
        "Indo-Greek",
        "Thaton",
        "Barghawata",
        "Idrisids",
        "Independent Cyprus",
        "Knights Templar",
        "Kintampo Culture",
        "Bonoman",
        "Bono",
        "Holland",
        "New Republic",
        "Britons",
        "Philippine Republic",
        "Selangor",
        "Bosnia",
        "Aksum",
        "Zagwe Dynasty",
        "Liguria",
        "Berg",
        "Kusaila",
        "Arevaci",
        "Taifa Of Zaragoza",
        "Volsinii",
        "Etruscan City-State Of Velzna",
        "Duchy Of Spoleto",
        "Pushyabhuti Dynasty",
        "Kent",
        "Sorbs",
        "Samos Empire",
        "Chutizi",
        "Rogaland",
        "Rygjafylki",
        "Marcomanni",
        "Burgundians",
        "Huns",
        "Prague-Korchak Culture",
        "Samos Realm",
        "Czech Slavs",
        "Bohemia",
        "Psouane",
        "Moravia",
        "Mycenaean Culture",
        "Protogeometric Culture",
        "Dorians",
        "Argolis",
        "Macedonian",
        "Geats",
        "Obotrites",
        "Circipanes",
        "East Anglia",
        "Gazikumukh Khanate",
        "Galicia-Volhynia",
        "Kpelle",
        "Mende Chiefdoms",
        "Kono Chiefdoms",
        "Switzerland",
        "Taifa Of Arcos",
        "Ukrainian State",
        "Zulu",
        "Jaffna",
        "Valluvanad",
        "Calicut",
        "Pechenegs",
        "Genoa",
        "Former Liang",
        "Northern Liang",
        "Guiyi",
        "Lugii",
        "Przeworsk Culture",
        "Lugi",
        "White Croats",
        "Lendians",
        "Alamanni",
        "Taifa Of Saltes And Huelva",
        "Tartessos",
        "Turdetani",
        "Polans",
        "Duchy Of Poland",
        "Quraysh",
        "Krivichs",
        "Kolochin Culture",
        "Lebanon",
        "Allied Powers",
        "Songhai",
        "Dendi",
        "Mali Empire",
        "Bamana Empire",
        "Massina",
        "Toucouleur Empire",
        "Mnla/Ansar Dine",
        "Waalo",
        "Taino",
        "Lan Xang",
        "Hafsid Sultanate",
        "Hesse",
        "Aro Confederacy",
        "Treviso",
        "Kaabu",
        "East Geats",
        "Later Guptas",
        "Tonga",
        "Polynesians",
        "Tongan Chiefdoms",
        "Lotharingia",
        "Buganda",
        "Namibia",
        "Grenadine Confederation",
        "Purepecha Empire",
        "English Commonwealth",
        "Syrian National Army",
        "Melingoi",
        "Koinon Of Free Laconians",
        "Lepreon",
        "Elis",
        "Chalcidia",
        "Thebes",
        "Waliship Of Al-Andalus",
        "Taifa Of Lleida",
        "Western Ganga Dynasty",
        "Vermont Republic",
        "Kakongo",
        "Tarascan State",
        "Solomon Islands",
        "Carnatic",
        "Catepanate Of Italy",
        "Chola Dynasty",
        "Batibo",
        "Chitarero Chiefdom",
        "First Philippine Republic",
        "Virginia",
        "Majerteen Sultanate",
        "Hariphunchai",
        "Silingi Vandals",
        "Hammudid Caliphate",
        "Taifa Of Malaga",
        "League Of Nations",
        "Ukrainian Soviet Republic",
        "Byzantine Italy",
        "Cisalpine Republic",
        "Kasa",
        "Acalan",
        "Cuauhnahuac",
        "Nuragic Culture",
        "Treveri",
        "Encheleans",
        "Illyria",
        "Ardiaei",
        "Antigonid Macedon",
        "Berziti",
        "Berziti Slavs",
        "Bulgarian Empire Cometopuli",
        "Perugia",
        "Ordovices",
        "Deceangli",
        "Delmatae",
        "Domain Of Marcellinus",
        "Domain Of Julius Nepos",
        "Amisos",
        "Paphlagonians",
        "Miletus",
        "Ankara Government",
        "Bronze Age Irish",
        "Connacht",
        "Thessaly",
        "Taifa Of Badajoz",
        "Rhegion",
        "Bruttii",
        "Mamertines",
        "Yaudheya",
        "Chauhans",
        "Visigoths",
        "Asturia",
        "Mauritania",
        "Berbers",
        "Mauretania",
        "Castro Culture",
        "Toltec Empire",
        "Republic Of Venice",
        "Aymara States",
        "Killke Culture",
        "Cusco",
        "Cuzco",
        "Inca",
        "Caranqui",
        "Quito",
        "Caranqui Confederation",
        "Tamna",
        "Wa Japan",
        "Gauda",
        "Pushyabhuti Dynasty Harsha",
        "Khadga Dynasty",
        "Qatar",
        "Igbo Polities",
        "Orkney Neolithic Culture",
        "Drevlians",
        "Tuyuhun",
        "Northern Caucasus",
        "Mosquito",
        "British Cape Colony",
        "Saqqawist",
        "Lima Culture",
        "Wari Empire",
        "Ichma",
        "Baden",
        "Novgorod",
        "Jamaica",
        "Elba Napoleon",
        "First Spanish Republic",
        "Al-Jazira Upper Mesopotamia",
        "Syrian Arab Republic",
        "Uncontrolled/War Zone",
        "Sican Culture",
        "Chimor",
        "Western Kshatrapas",
        "Aulikara Dynasty",
        "Min",
        "Min Ten",
        "South Carolina",
        "Allied Occupation",
        "Equatorial Guinea",
        "Eritrea",
        "Pyu",
        "Later Baekje",
        "Anuradhapura",
        "Bactria-Margiana Culture",
        "Bactria",
        "Kara Khitan",
        "Koliya",
        "Kosala",
        "Shunga"
    ]

    target_name_1 = "Dutch Empire"
    target_name_2 = "Dutch"
    test_class = NamesSearch(names)
    results = test_class.search_for_similar_names(target_name_1)
    print(f"Results for '{target_name_1}': {results}")
    results = test_class.search_for_similar_names(target_name_2)
    print(f"Results for '{target_name_2}': {results}")